=== 0x7678/MDM-1/conf/mdm_request.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespaces="http://www.mg.com.ar/MDM-Protocol" xmlns="http://www.mg.com.ar/MDM-Protocol"
	elementFormDefault="qualified"
>

<xs:element name="mdm_request">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="version" type="xs:string" fixed="0.1.2"/>
			<xs:element name="device">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="connection">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="target" maxOccurs="1" minOccurs="1" type="xs:string"/>
						<xs:element name="type">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="0"/>
									<xs:maxInclusive value="10"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="connect_timeout">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="recv_timeout">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="credential">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="username" maxOccurs="1" minOccurs="1" type="xs:string"/>
									<xs:element name="password" maxOccurs="1" minOccurs="1" type="xs:string"/>
									<xs:element name="enable" maxOccurs="1" minOccurs="0" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="command">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="type">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="0"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="arguments" maxOccurs="1" minOccurs="0" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== 0x7678/MDM-1/conf/mdm_request_example.xml
<?xml version="1.0" encoding="UTF-8"?>

<mdm_request
	xmlns:mdm="http://www.mg.com.ar/MDM-Protocol"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mg.com.ar/MDM mdm_request.xsd"
>
	<device>0</device>
	<connection>
		<target>190.13.224.61:23</target>
		<type>0</type>
		<credential>
			<username>isadmin</username>
			<password>tbsa_2008</password>
		</credential>
	</connection>
	<command>
		<type>23</type>
		<arguments>1/1/1/1</arguments>
	</command>
</mdm_request>

<!--
<?xml version="1.0" encoding="UTF-8"?>

<mdm_request
	xmlns:mdm="http://www.mg.com.ar/MDM-Protocol"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mg.com.ar/MDM mdm_request.xsd"
>
	<device>0</device>
	<connection>
		<target>190.13.224.61:23</target>
		<type>0</type>
		<credential>
			<username>isadmin</username>
			<password>tbsa_2008</password>
		</credential>
	</connection>
	<command>
		<type>2</type>
	</command>
</mdm_request>


<?xml version="1.0" encoding="UTF-8"?>

<mdm_request
	xmlns:mdm="http://www.mg.com.ar/MDM-Protocol"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mg.com.ar/MDM mdm_request.xsd"
>
	<device>1</device>
	<connection>
		<target>192.168.0.4:23</target>
		<type>0</type>
		<credential>
			<username>root</username>
			<password>root</password>
		</credential>
	</connection>
	<command>
		<type>3</type>
	</command>
</mdm_request>

<?xml version="1.0" encoding="UTF-8"?>

<mdm_request
	xmlns:mdm="http://www.mg.com.ar/MDM-Protocol"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mg.com.ar/MDM mdm_request.xsd"
>
	<device>1</device>
	<connection>
		<target>/dev/cuad0</target>
		<type>7</type>
		<credential>
			<username>root</username>
			<password>root</password>
		</credential>
	</connection>
	<command>
		<type>1</type>
	</command>
</mdm_request>


-->
